export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY";

export const GET_CATEGORY_BY_ID = "GET_CATEGORY_BY_ID";

export const SAVE_CATEGORY = "SAVE_CATEGORY";

export const UPDATE_CATEGORY = "UPDATE_CATEGORY";

export const DELETE_CATEGORY = "DELETE_CATEGORY";

export const CATEGORY_SUCCESS = "CATEGORY_SUCCESS";

export const CATEGORY_FAILURE = "CATEGORY_FAILURE";
